backend:
  name: github
  repo: jd-fillmore/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Text, name: heroText, widget: text }
          - { label: My Image, name: myImage, widget: image }
